services:
  - type: worker
    name: alpaca-momentum-trading-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: API_KEY
        sync: false
      - key: SECRET_KEY
        sync: false